drop schema if exists app cascade;
create schema app;

drop table if exists public.financial_entries cascade;
drop table if exists public.task_comments cascade;
drop table if exists public.tasks cascade;
drop table if exists public.projects cascade;
drop table if exists public.collaborators cascade;
drop table if exists public.departments cascade;
drop table if exists public.workspaces cascade;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.touch_task_from_comment()
returns trigger
language plpgsql
as $$
begin
  update public.tasks
  set last_commented_at = now(),
      updated_at = now()
  where id = new.task_id;

  return new;
end;
$$;

create table public.workspaces (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.departments (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces(id) on delete cascade,
  name text not null,
  slug text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, slug)
);

create table public.collaborators (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces(id) on delete cascade,
  department_id integer references public.departments(id) on delete set null,
  full_name text not null,
  email text,
  role public.workspace_role not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.projects (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces(id) on delete cascade,
  department_id integer not null references public.departments(id) on delete restrict,
  name text not null,
  description text,
  status public.project_status not null default 'active',
  progress integer not null default 0 check (progress between 0 and 100),
  created_by integer references public.collaborators(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, name)
);

create table public.tasks (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces(id) on delete cascade,
  project_id integer not null references public.projects(id) on delete cascade,
  title text not null,
  description text,
  status public.task_status not null default 'todo',
  priority public.task_priority not null default 'medium',
  risk public.task_risk not null default 'low',
  assignee_id integer references public.collaborators(id) on delete set null,
  assigned_by integer references public.collaborators(id) on delete set null,
  due_date date,
  position numeric(12, 3) not null default 1000,
  created_by integer references public.collaborators(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status_updated_at timestamptz not null default now(),
  last_commented_at timestamptz
);

create table public.task_comments (
  id integer generated by default as identity primary key,
  task_id integer not null references public.tasks(id) on delete cascade,
  author_id integer references public.collaborators(id) on delete set null,
  body text not null check (char_length(trim(body)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.financial_entries (
  id integer generated by default as identity primary key,
  workspace_id integer not null references public.workspaces(id) on delete cascade,
  department_id integer references public.departments(id) on delete set null,
  period_start date not null,
  revenue integer not null default 0 check (revenue >= 0),
  expenses integer not null default 0 check (expenses >= 0),
  profit integer not null check (profit = revenue - expenses),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_start = date_trunc('month', period_start)::date)
);

create index idx_departments_workspace on public.departments(workspace_id);
create index idx_collaborators_workspace on public.collaborators(workspace_id);
create index idx_collaborators_department on public.collaborators(department_id);
create index idx_projects_workspace_department on public.projects(workspace_id, department_id);
create index idx_tasks_workspace_project on public.tasks(workspace_id, project_id);
create index idx_tasks_assignee on public.tasks(assignee_id);
create index idx_task_comments_task_created on public.task_comments(task_id, created_at desc);
create index idx_financial_entries_workspace_period
  on public.financial_entries(workspace_id, period_start desc)
  where department_id is null;
create index idx_financial_entries_workspace_department_period
  on public.financial_entries(workspace_id, department_id, period_start desc)
  where department_id is not null;
create unique index uq_financial_entries_workspace_period_global
  on public.financial_entries(workspace_id, period_start)
  where department_id is null;
create unique index uq_financial_entries_workspace_department_period
  on public.financial_entries(workspace_id, department_id, period_start)
  where department_id is not null;

drop trigger if exists trg_workspaces_set_updated_at on public.workspaces;
create trigger trg_workspaces_set_updated_at
before update on public.workspaces
for each row execute function public.set_updated_at();

drop trigger if exists trg_departments_set_updated_at on public.departments;
create trigger trg_departments_set_updated_at
before update on public.departments
for each row execute function public.set_updated_at();

drop trigger if exists trg_collaborators_set_updated_at on public.collaborators;
create trigger trg_collaborators_set_updated_at
before update on public.collaborators
for each row execute function public.set_updated_at();

drop trigger if exists trg_projects_set_updated_at on public.projects;
create trigger trg_projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists trg_tasks_set_updated_at on public.tasks;
create trigger trg_tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists trg_task_comments_set_updated_at on public.task_comments;
create trigger trg_task_comments_set_updated_at
before update on public.task_comments
for each row execute function public.set_updated_at();

drop trigger if exists trg_financial_entries_set_updated_at on public.financial_entries;
create trigger trg_financial_entries_set_updated_at
before update on public.financial_entries
for each row execute function public.set_updated_at();

drop trigger if exists trg_touch_task_from_comment on public.task_comments;
create trigger trg_touch_task_from_comment
after insert on public.task_comments
for each row execute function public.touch_task_from_comment();

grant usage on schema public to anon;
grant usage on schema public to authenticated;

grant select, insert, update, delete on
  public.workspaces,
  public.departments,
  public.collaborators,
  public.projects,
  public.tasks,
  public.task_comments,
  public.financial_entries
to anon;

grant select, insert, update, delete on
  public.workspaces,
  public.departments,
  public.collaborators,
  public.projects,
  public.tasks,
  public.task_comments,
  public.financial_entries
to authenticated;

grant usage, select on all sequences in schema public to anon;
grant usage, select on all sequences in schema public to authenticated;

alter table public.workspaces enable row level security;
alter table public.departments enable row level security;
alter table public.collaborators enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.task_comments enable row level security;
alter table public.financial_entries enable row level security;

create policy "workspaces_anon_all"
on public.workspaces
for all
to anon
using (true)
with check (true);

create policy "departments_anon_all"
on public.departments
for all
to anon
using (true)
with check (true);

create policy "collaborators_anon_all"
on public.collaborators
for all
to anon
using (true)
with check (true);

create policy "projects_anon_all"
on public.projects
for all
to anon
using (true)
with check (true);

create policy "tasks_anon_all"
on public.tasks
for all
to anon
using (true)
with check (true);

create policy "task_comments_anon_all"
on public.task_comments
for all
to anon
using (true)
with check (true);

create policy "financial_entries_anon_all"
on public.financial_entries
for all
to anon
using (true)
with check (true);

create policy "workspaces_authenticated_all"
on public.workspaces
for all
to authenticated
using (true)
with check (true);

create policy "departments_authenticated_all"
on public.departments
for all
to authenticated
using (true)
with check (true);

create policy "collaborators_authenticated_all"
on public.collaborators
for all
to authenticated
using (true)
with check (true);

create policy "projects_authenticated_all"
on public.projects
for all
to authenticated
using (true)
with check (true);

create policy "tasks_authenticated_all"
on public.tasks
for all
to authenticated
using (true)
with check (true);

create policy "task_comments_authenticated_all"
on public.task_comments
for all
to authenticated
using (true)
with check (true);

create policy "financial_entries_authenticated_all"
on public.financial_entries
for all
to authenticated
using (true)
with check (true);
